const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'movie-admin-'));
process.env.DATA_FILE = path.join(temp, 'data.json');
const app = require('./index');

test('Admin and staff permissions, settings, episodes, homepage and dated statistics', async t => {
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => { server.close(); const resolved = fs.realpathSync(temp); assert.ok(resolved.startsWith(fs.realpathSync(os.tmpdir()) + path.sep)); fs.rmSync(resolved, { recursive:true, force:true }); });
  async function req(url, method='GET', body, cookie) {
    const r=await fetch(`http://127.0.0.1:${server.address().port}/api${url}`, { method, headers:{'Content-Type':'application/json', ...(cookie ? {cookie}: {})}, body:body ? JSON.stringify(body):undefined });
    return { status:r.status, data:await r.json(), cookie:r.headers.get('set-cookie')?.split(';')[0] };
  }
  const password='test-only-password-123';
  const admin=await req('/auth/setup','POST',{email:'admin@example.test',password});
  const staff=await req('/auth/register','POST',{email:'staff@example.test',password,role:'admin'});
  const user=await req('/auth/register','POST',{email:'viewer@example.test',password});
  assert.equal(staff.data.role,'user');
  assert.ok(user.data.created_at);
  assert.equal((await req('/admin','GET',null,user.cookie)).status,403);
  assert.equal((await req('/admin/users/'+staff.data.id,'PATCH',{role:'staff'},admin.cookie)).status,200);
  assert.equal((await req('/admin','GET',null,staff.cookie)).status,200);
  assert.deepEqual((await req('/admin','GET',null,staff.cookie)).data.users,[]);
  for (const prefix of ['/admin/settings','/ADMIN/settings']) assert.equal((await req(prefix,'PUT',{name:'No'},staff.cookie)).status,403);
  assert.equal((await req('/admin/users/'+user.data.id,'PATCH',{role:'admin'},staff.cookie)).status,403);
  assert.equal((await req('/admin/users/'+user.data.id,'PATCH',{role:'owner'},admin.cookie)).status,400);
  assert.equal((await req('/admin/users/'+admin.data.id,'PATCH',{deleted:true},admin.cookie)).status,400);
  assert.equal((await req('/admin/settings','PUT',{registration_enabled:false,comments_enabled:false,logo:'/storage/logo.png',favicon:'/storage/icon.png',footer:'Test footer'},admin.cookie)).status,200);
  assert.equal((await req('/auth/register','POST',{email:'closed@example.test',password})).status,403);
  assert.equal((await req('/admin/settings','PUT',{registration_enabled:'false'},admin.cookie)).status,400);
  const movie={name:'Admin test movie',slug:'admin-test',status:'ongoing',type:'series',categories:[],regions:[],episodes:[{id:'a',slug:'a',name:'01',server:'Server 1',language:'Vietsub',type:'mp4',link:'https://example.test/a.mp4',order:0,is_new:true},{id:'b',slug:'b',name:'01',server:'Server 2',language:'Lồng tiếng',type:'m3u8',link:'https://example.test/b.m3u8',order:1}]};
  const initial=(await req('/admin/statistics','GET',null,staff.cookie)).data;
  const created=await req('/admin/movies','POST',movie,staff.cookie);
  assert.equal(created.status,200);
  assert.equal((await req('/admin/movies','POST',movie,staff.cookie)).status,409);
  assert.equal((await req('/movies/admin-test/comments','POST',{text:'Closed'},user.cookie)).status,403);
  assert.equal((await req('/admin/settings','PUT',{registration_enabled:true,comments_enabled:true},admin.cookie)).status,200);
  assert.equal((await req('/movies/admin-test/comments','POST',{text:'Open'},user.cookie)).status,200);
  await req('/movies/admin-test/view','POST',{});
  const updated=await req('/admin/movies','POST',{...created.data,episodes:[{...movie.episodes[1],order:0},{...movie.episodes[0],order:1}],view_total:0,daily_views:{}},staff.cookie);
  assert.equal(updated.data.view_total,1);
  assert.equal(updated.data.created_at,created.data.created_at);
  assert.equal(updated.data.episodes[0].language,'Lồng tiếng');
  assert.equal((await req('/admin/movies/'+created.data.id,'PATCH',{is_recommended:true,homepage_top:true},staff.cookie)).status,200);
  assert.equal((await req('/admin/movies/'+created.data.id,'PATCH',{is_hot:'false'},staff.cookie)).status,400);
  const catalogue=(await req('/catalog')).data;
  assert.equal(catalogue.movies.find(m=>m.slug===movie.slug).homepage_top,true);
  assert.equal(catalogue.settings.footer,'Test footer');
  const stats=(await req('/admin/statistics','GET',null,staff.cookie)).data;
  assert.equal(stats.days.length,30);assert.equal(stats.months.length,12);
  assert.equal(stats.totals.episodes,initial.totals.episodes+1);
  assert.equal(stats.totals.movies,initial.totals.movies+1);
  assert.equal(stats.totals.today,1);assert.equal(stats.totals.month,1);
  assert.equal(stats.totals.newUsers,3);assert.equal(stats.totals.newComments,1);
  assert.equal(stats.newest[0].slug,'admin-test');
  await req('/admin/users/'+staff.data.id,'PATCH',{role:'user'},admin.cookie);
  assert.equal((await req('/admin/statistics','GET',null,staff.cookie)).status,403);
});
