const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'movie-features-'));
process.env.DATA_FILE = path.join(temp, 'data.json');
const app = require('./index');
test('Notifications, independent taxonomies, moderation and statistics', async t => {
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => { server.close(); fs.rmSync(temp, { recursive: true, force: true }); });
  const base = 'http://127.0.0.1:' + server.address().port + '/api';
  async function req(url, method = 'GET', body, cookie) {
    const r = await fetch(base + url, { method, headers: { 'Content-Type': 'application/json', ...(cookie ? { cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
    return { status: r.status, data: await r.json(), cookie: r.headers.get('set-cookie')?.split(';')[0] };
  }
  const admin = await req('/auth/setup', 'POST', { email: 'admin@example.test', password: 'test-password-123' });
  const user = await req('/auth/register', 'POST', { email: 'viewer@example.test', password: 'test-password-123' });
  const movie = { name: 'Feature test', slug: 'feature-test', categories: [], regions: [], episodes: [], type: 'series', status: 'ongoing' };
  const created = await req('/admin/movies', 'POST', movie, admin.cookie);
  assert.equal(created.status, 200);
  assert.equal((await req('/notifications', 'GET', null, user.cookie)).data.length, 1);
  await req('/profile', 'POST', { field: 'following', slug: movie.slug }, user.cookie);
  const edited = { ...created.data, episodes: [{ id: 'ep1', slug: 'ep1', name: '1', server: 'Vietsub', type: 'mp4', link: 'https://example.test/movie.mp4' }] };
  await req('/admin/movies', 'POST', edited, admin.cookie);
  await req('/admin/movies', 'POST', edited, admin.cookie);
  assert.equal((await req('/notifications', 'GET', null, user.cookie)).data.length, 2);
  assert.equal((await req('/notifications', 'GET', null, admin.cookie)).data.length, 1);
  await req('/notifications/read', 'POST', {}, user.cookie);
  assert.ok((await req('/notifications', 'GET', null, user.cookie)).data.every(n => n.read));
  await req('/notifications/preferences', 'PUT', { newMovies: false, newEpisodes: false }, user.cookie);
  await req('/admin/movies', 'POST', { ...movie, slug: 'second-test' }, admin.cookie);
  assert.equal((await req('/notifications', 'GET', null, user.cookie)).data.length, 2);
  const tax = await req('/admin/taxonomies/categories', 'POST', { name: 'Custom Category' }, admin.cookie);
  const entry = tax.data.find(c => c.name === 'Custom Category');
  assert.ok(entry);
  await req('/admin/taxonomies/categories', 'POST', { ...entry, deleted: true }, admin.cookie);
  assert.ok(!(await req('/catalog')).data.taxonomies.categories.some(c => c.id === entry.id));
  await req('/admin/taxonomies/categories', 'POST', { ...entry, deleted: false }, admin.cookie);
  assert.ok((await req('/catalog')).data.taxonomies.categories.some(c => c.id === entry.id));
  const comment = await req('/movies/feature-test/comments', 'POST', { text: 'Test comment' }, user.cookie);
  assert.equal((await req('/comments/' + comment.data.id + '/like', 'POST', {}, user.cookie)).data.count, 1);
  await req('/admin/comments/' + comment.data.id, 'PATCH', { deleted: true }, admin.cookie);
  assert.equal((await req('/movies/feature-test/community')).data.comments.length, 0);
  await req('/movies/feature-test/rating', 'POST', { score: 9 }, user.cookie);
  const rating = (await req('/movies/feature-test/community')).data.ratings[0];
  await req('/admin/ratings/' + rating.id, 'PATCH', { hidden: true }, admin.cookie);
  await req('/movies/feature-test/rating', 'POST', { score: 8 }, user.cookie);
  assert.equal((await req('/movies/feature-test/community')).data.ratings.length, 0);
  await req('/movies/feature-test/view', 'POST', {});
  assert.equal((await req('/admin/statistics', 'GET', null, admin.cookie)).data.days.at(-1).views, 1);
  await req('/admin/users/' + user.data.id, 'PATCH', { deleted: true }, admin.cookie);
  assert.equal((await req('/notifications', 'GET', null, user.cookie)).status, 401);
});
