const { test } = require('node:test');
const assert = require('node:assert/strict');
const os = require('os');
const path = require('path');
const fs = require('fs');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'motchill-test-'));
process.env.DATA_FILE = path.join(temp, 'data.json');
const app = require('./index');
test('Authentication, permissions, catalogue edits, community and persistence', async t => {
  const server = app.listen(0, '127.0.0.1');
  await new Promise(resolve => server.once('listening', resolve));
  t.after(() => { server.close(); fs.rmSync(temp, { recursive: true, force: true }); });
  const base = 'http://127.0.0.1:' + server.address().port;
  async function request(url, method = 'GET', body, cookie) {
    const r = await fetch(base + '/api' + url, { method, headers: { 'Content-Type': 'application/json', ...(cookie ? { cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
    return { status: r.status, body: await r.json(), cookie: r.headers.get('set-cookie')?.split(';')[0] };
  }
  assert.equal((await request('/admin')).status, 403);
  assert.equal((await request('/session')).body.needsSetup, true);
  const admin = await request('/auth/setup', 'POST', { name: 'Admin Test', email: 'admin@example.test', password: 'test-password-123' });
  assert.equal(admin.body.role, 'admin');
  assert.equal(admin.body.hash, undefined);
  assert.equal((await request('/auth/setup', 'POST', { email: 'second@example.test', password: 'test-password-123' })).status, 403);
  const user = await request('/auth/register', 'POST', { name: 'Viewer Test', email: 'viewer@example.test', password: 'test-password-456', role: 'admin' });
  assert.equal(user.body.role, 'user');
  assert.equal((await request('/admin', 'GET', null, user.cookie)).status, 403);
  const { movies } = (await request('/catalog')).body;
  assert.ok(movies.length >= 100);
  const movie = { ...movies[0], slug: 'test-movie', name: 'Test Movie' };
  assert.equal((await request('/admin/movies', 'POST', movie, user.cookie)).status, 403);
  const added = (await request('/admin/movies', 'POST', movie, admin.cookie)).body;
  assert.equal(added.name, 'Test Movie');
  await request('/admin/movies/' + added.id, 'PATCH', { deleted: true }, admin.cookie);
  assert.ok(!(await request('/catalog')).body.movies.some(m => m.slug === movie.slug));
  await request('/admin/movies/' + added.id, 'PATCH', { deleted: false }, admin.cookie);
  assert.ok((await request('/catalog')).body.movies.some(m => m.slug === movie.slug));
  assert.equal((await request('/movies/test-movie/comments', 'POST', { text: 'hello' })).status, 401);
  const comment = await request('/movies/test-movie/comments', 'POST', { text: 'A useful test comment' }, user.cookie);
  assert.equal(comment.status, 200);
  await request('/admin/comments/' + comment.body.id, 'PATCH', { hidden: true }, admin.cookie);
  assert.equal((await request('/movies/test-movie/community')).body.comments.length, 0);
  await request('/movies/test-movie/rating', 'POST', { score: 8 }, user.cookie);
  await request('/movies/test-movie/rating', 'POST', { score: 9 }, user.cookie);
  const ratings = (await request('/movies/test-movie/community')).body.ratings;
  assert.equal(ratings.length, 1); assert.equal(ratings[0].score, 9);
  assert.equal((await request('/movies/test-movie/rating', 'POST', { score: 11 }, user.cookie)).status, 400);
  const profile = await request('/profile', 'POST', { field: 'favorites', slug: 'test-movie' }, user.cookie);
  assert.ok(profile.body.favorites.includes('test-movie'));
  await request('/profile', 'POST', { field: 'history', slug: 'test-movie', episode: 'one', progress: 42 }, user.cookie);
  assert.equal((await request('/session', 'GET', null, user.cookie)).body.user.history[0].progress, 42);
  assert.equal((await request('/reports', 'POST', { message: 'Video unavailable', slug: 'test-movie' })).status, 200);
  assert.equal((await request('/admin', 'GET', null, admin.cookie)).body.reports.length, 1);
  await request('/admin/users/' + user.body.id, 'PATCH', { blocked: true }, admin.cookie);
  assert.equal((await request('/profile', 'POST', { field: 'name', name: 'Blocked' }, user.cookie)).status, 401);
  assert.equal((await request('/admin/users/' + admin.body.id, 'PATCH', { blocked: true }, admin.cookie)).status, 400);
  const stored = JSON.parse(fs.readFileSync(process.env.DATA_FILE));
  assert.equal(stored.users[0].password, undefined);
  assert.ok(stored.users[0].hash.length === 128);
  assert.ok(stored.movies.some(m => m.slug === 'test-movie'));
  await request('/auth/logout', 'POST', null, admin.cookie);
  assert.equal((await request('/admin', 'GET', null, admin.cookie)).status, 403);
});
