const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const dataFile = path.join(__dirname, '..', 'server', 'data.json');
const catalogFile = path.join(__dirname, '..', 'server', 'catalog.json');

const db = fs.existsSync(dataFile) ? JSON.parse(fs.readFileSync(dataFile, 'utf8')) : { movies: [] };

const extraMovies = [
  {
    name: 'Mai',
    origin_name: 'Mai',
    slug: 'mai-2024',
    thumb_url: 'https://image.tmdb.org/t/p/w500/b0Onv4bK7fD5d5aT8Q4aT1v7w5V.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/mBaXZkOxN6u9W4V1n3Q9A7m7pY.jpg',
    type: 'single',
    status: 'completed',
    episode_time: '131 phút',
    episode_current: 'Full HD',
    episode_total: '1',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2024,
    is_shown_in_theater: true,
    is_recommended: true,
    is_hot: true,
    view_total: 2894500,
    view_day: 45200,
    view_week: 312000,
    view_month: 850000,
    rating_count: 8520,
    rating_star: '9.2',
    categories: [{ id: '2', name: 'Tình Cảm', slug: 'tinh-cam' }, { id: '5', name: 'Tâm Lý', slug: 'tam-ly' }, { id: '18', name: 'Chính kịch', slug: 'chinh-kich' }],
    regions: [{ id: '40', name: 'Việt Nam', slug: 'viet-nam' }],
    description: 'Mai kể về cuộc đời của người phụ nữ cùng tên do Phương Anh Đào thủ vai. Mai là nhân viên massage, mẹ đơn thân, luôn chịu nhiều định kiến xã hội. Cuộc đời cô bước sang trang mới khi gặp Dương (Tuấn Trần), chàng công tử đào hoa kém tuổi.',
    actor: 'Phương Anh Đào, Tuấn Trần, Trấn Thành, Hồng Đào, Uyển Ân',
    director: 'Trấn Thành',
    episodes: [
      { id: 'ep-mai-1', movie_id: 'mai-2024', server: 'Server VIP (K-Vietsub)', name: 'Full', slug: 'full-vip', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260826/3hQ5mFzr/index.m3u8' },
      { id: 'ep-mai-2', movie_id: 'mai-2024', server: 'Server Dự Phòng (V-Vietsub)', name: 'Full', slug: 'full-backup', type: 'm3u8', link: 'https://v8.streamvsmov.com/stream/82a5b5ad-7482-418a-b181-9929703b94ac/master.m3u8' }
    ]
  },
  {
    name: 'Lật Mặt 7: Một Điều Ước',
    origin_name: 'Face Off 7: One Wish',
    slug: 'lat-mat-7-mot-dieu-uoc',
    thumb_url: 'https://image.tmdb.org/t/p/w500/8c0N3X3o2V4aT1v7w5Vb0Onv4bK.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/mBaXZkOxN6u9W4V1n3Q9A7m7pY.jpg',
    type: 'single',
    status: 'completed',
    episode_time: '138 phút',
    episode_current: 'Full HD',
    episode_total: '1',
    quality: 'FHD',
    language: 'Lồng Tiếng',
    publish_year: 2024,
    is_shown_in_theater: true,
    is_recommended: true,
    is_hot: true,
    view_total: 3120000,
    view_day: 51200,
    view_week: 420000,
    view_month: 980000,
    rating_count: 9410,
    rating_star: '9.4',
    categories: [{ id: '68', name: 'Gia Đình', slug: 'gia-dinh' }, { id: '5', name: 'Tâm Lý', slug: 'tam-ly' }, { id: '18', name: 'Chính kịch', slug: 'chinh-kich' }],
    regions: [{ id: '40', name: 'Việt Nam', slug: 'viet-nam' }],
    description: 'Bộ phim xoay quanh câu chuyện gia đình bà Hai 73 tuổi cùng 5 người con trưởng thành lập nghiệp ở khắp nơi. Một biến cố xảy ra khiến những người con phải đối mặt với câu hỏi ai sẽ chăm sóc mẹ già.',
    actor: 'Thanh Hiền, Trương Minh Cường, Đinh Y Nhung, Quách Ngọc Tuyên, Trâm Anh',
    director: 'Lý Hải',
    episodes: [
      { id: 'ep-lm7-1', movie_id: 'lat-mat-7', server: 'Server VIP (K-Vietsub)', name: 'Full', slug: 'full-vip', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260826/57ip9H9r/index.m3u8' },
      { id: 'ep-lm7-2', movie_id: 'lat-mat-7', server: 'Server Thuyết Minh', name: 'Full', slug: 'full-tm', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260831/ljjy0751/index.m3u8' }
    ]
  },
  {
    name: 'Nữ Hoàng Nước Mắt',
    origin_name: 'Queen of Tears',
    slug: 'nu-hoang-nuoc-mat-queen-of-tears',
    thumb_url: 'https://image.tmdb.org/t/p/w500/6y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/9y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    type: 'series',
    status: 'completed',
    episode_time: '70 phút/tập',
    episode_current: 'Hoàn Tất (16/16)',
    episode_total: '16',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2024,
    is_shown_in_theater: false,
    is_recommended: true,
    is_hot: true,
    view_total: 4500000,
    view_day: 82000,
    view_week: 540000,
    view_month: 1500000,
    rating_count: 12500,
    rating_star: '9.6',
    categories: [{ id: '2', name: 'Tình Cảm', slug: 'tinh-cam' }, { id: '3', name: 'Hài Hước', slug: 'hai-huoc' }, { id: '18', name: 'Chính kịch', slug: 'chinh-kich' }],
    regions: [{ id: '2', name: 'Hàn Quốc', slug: 'han-quoc' }],
    description: 'Nữ hoàng trung tâm thương mại và hoàng tử siêu thị trải qua một cuộc khủng hoảng hôn nhân – cho đến khi tình yêu bắt đầu nảy nở trở lại một cách kỳ diệu.',
    actor: 'Kim Soo-hyun, Kim Ji-won, Park Sung-hoon, Kwak Dong-yeon, Lee Joo-bin',
    director: 'Jang Young-woo, Kim Hee-won',
    episodes: Array.from({ length: 16 }, (_, i) => ({
      id: `qot-ep-${i + 1}`,
      movie_id: 'queen-of-tears',
      server: 'Server VIP (K-Vietsub)',
      name: `Tập ${String(i + 1).padStart(2, '0')}`,
      slug: `tap-${i + 1}`,
      type: 'm3u8',
      link: 'https://v7.kkphimplayer7.com/20260826/3hQ5mFzr/index.m3u8'
    }))
  },
  {
    name: 'Vua Hải Tặc: One Piece',
    origin_name: 'One Piece',
    slug: 'one-piece-vua-hai-tac',
    thumb_url: 'https://image.tmdb.org/t/p/w500/cMD9Ygz11xYxfGcuIDBJu9ioC9g.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/4Mt7whox67MBLEManeMiootorG2.jpg',
    type: 'series',
    status: 'ongoing',
    episode_time: '24 phút/tập',
    episode_current: 'Tập 1120',
    episode_total: '1200',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2024,
    is_shown_in_theater: false,
    is_recommended: true,
    is_hot: true,
    view_total: 9800000,
    view_day: 120000,
    view_week: 890000,
    view_month: 2500000,
    rating_count: 24500,
    rating_star: '9.8',
    categories: [{ id: '92', name: 'Anime & Hoạt Hình', slug: 'hoat-hinh' }, { id: '1', name: 'Hành Động', slug: 'hanh-dong' }, { id: '11', name: 'Phiêu Lưu', slug: 'phieu-luu' }],
    regions: [{ id: '3', name: 'Nhật Bản', slug: 'nhat-ban' }],
    description: 'Monkey D. Luffy, một cậu bé mang ước mơ trở thành Vua Hải Tặc, bắt đầu hành trình tìm kiếm kho báu huyền thoại One Piece cùng băng Mũ Rơm.',
    actor: 'Mayumi Tanaka, Akemi Okamura, Kazuya Nakai, Kappei Yamaguchi, Hiroaki Hirata',
    director: 'Konosuke Uda',
    episodes: Array.from({ length: 24 }, (_, i) => ({
      id: `op-ep-${i + 1}`,
      movie_id: 'one-piece',
      server: 'Server VIP (K-Vietsub)',
      name: `Tập ${String(i + 1).padStart(2, '0')}`,
      slug: `tap-${i + 1}`,
      type: 'm3u8',
      link: 'https://v7.kkphimplayer7.com/20260831/ljjy0751/index.m3u8'
    }))
  },
  {
    name: 'Thám Tử Lừng Danh Conan',
    origin_name: 'Detective Conan',
    slug: 'tham-tu-lung-danh-conan',
    thumb_url: 'https://image.tmdb.org/t/p/w500/3Uhp0h7Qd3xV4aT1v7w5Vb0Onv4bK.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/5Uhp0h7Qd3xV4aT1v7w5Vb0Onv4bK.jpg',
    type: 'series',
    status: 'ongoing',
    episode_time: '24 phút/tập',
    episode_current: 'Tập 1135',
    episode_total: '1200',
    quality: 'FHD',
    language: 'Vietsub + Lồng Tiếng',
    publish_year: 2024,
    is_shown_in_theater: false,
    is_recommended: true,
    is_hot: true,
    view_total: 8200000,
    view_day: 95000,
    view_week: 720000,
    view_month: 2100000,
    rating_count: 19800,
    rating_star: '9.7',
    categories: [{ id: '92', name: 'Anime & Hoạt Hình', slug: 'hoat-hinh' }, { id: '19', name: 'Bí ẩn', slug: 'bi-an' }, { id: '6', name: 'Hình Sự', slug: 'hinh-su' }],
    regions: [{ id: '3', name: 'Nhật Bản', slug: 'nhat-ban' }],
    description: 'Kudo Shinichi, một thám tử trung học tài ba, bị Tổ Chức Áo Đen đầu độc khiến cơ thể teo nhỏ thành đứa trẻ tiểu học. Dưới thân phận Edogawa Conan, cậu tiếp tục phá giải những vụ án hóc búa.',
    actor: 'Minami Takayama, Wakana Yamazaki, Akira Kamiya, Megumi Hayashibara',
    director: 'Kenji Kodama, Yasuichiro Yamamoto',
    episodes: Array.from({ length: 20 }, (_, i) => ({
      id: `conan-ep-${i + 1}`,
      movie_id: 'conan',
      server: 'Server VIP (K-Vietsub)',
      name: `Tập ${String(i + 1).padStart(2, '0')}`,
      slug: `tap-${i + 1}`,
      type: 'm3u8',
      link: 'https://v7.kkphimplayer7.com/20260826/3hQ5mFzr/index.m3u8'
    }))
  },
  {
    name: 'Deadpool & Wolverine',
    origin_name: 'Deadpool & Wolverine',
    slug: 'deadpool-and-wolverine-2024',
    thumb_url: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    type: 'single',
    status: 'completed',
    episode_time: '128 phút',
    episode_current: 'Full HD',
    episode_total: '1',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2024,
    is_shown_in_theater: true,
    is_recommended: true,
    is_hot: true,
    view_total: 5120000,
    view_day: 78000,
    view_week: 590000,
    view_month: 1800000,
    rating_count: 14200,
    rating_star: '9.3',
    categories: [{ id: '1', name: 'Hành Động', slug: 'hanh-dong' }, { id: '3', name: 'Hài Hước', slug: 'hai-huoc' }, { id: '10', name: 'Viễn Tưởng', slug: 'vien-tuong' }],
    regions: [{ id: '46', name: 'Mỹ', slug: 'my' }, { id: '5', name: 'Âu Mỹ', slug: 'au-my' }],
    description: 'Wade Wilson mệt mỏi với cuộc sống thường nhật và buông bỏ thân phận Deadpool. Nhưng khi vũ trụ đối mặt với sự hủy diệt, anh phải hợp tác với một Wolverine bất đắc dĩ để giải cứu thế giới.',
    actor: 'Ryan Reynolds, Hugh Jackman, Emma Corrin, Morena Baccarin, Rob Delaney',
    director: 'Shawn Levy',
    episodes: [
      { id: 'ep-dpw-1', movie_id: 'deadpool-wolverine', server: 'Server VIP (K-Vietsub)', name: 'Full', slug: 'full-vip', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260820/Bg8E38Qv/index.m3u8' },
      { id: 'ep-dpw-2', movie_id: 'deadpool-wolverine', server: 'Server Thuyết Minh', name: 'Full', slug: 'full-tm', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260826/57ip9H9r/index.m3u8' }
    ]
  },
  {
    name: 'Trường Nguyệt Tẫn Minh',
    origin_name: 'Till The End Of The Moon',
    slug: 'truong-nguyet-tan-minh',
    thumb_url: 'https://image.tmdb.org/t/p/w500/2y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/3y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    type: 'series',
    status: 'completed',
    episode_time: '45 phút/tập',
    episode_current: 'Hoàn Tất (40/40)',
    episode_total: '40',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2023,
    is_shown_in_theater: false,
    is_recommended: true,
    is_hot: true,
    view_total: 6700000,
    view_day: 65000,
    view_week: 480000,
    view_month: 1600000,
    rating_count: 16500,
    rating_star: '9.5',
    categories: [{ id: '4', name: 'Cổ Trang', slug: 'co-trang' }, { id: '2', name: 'Tình Cảm', slug: 'tinh-cam' }, { id: '60', name: 'Thần Thoại', slug: 'than-thoai' }],
    regions: [{ id: '1', name: 'Trung Quốc', slug: 'trung-quoc' }],
    description: 'Để cứu vớt tam giới khỏi Ma thần Đạm Đài Tẫn, Lê Tô Tô – con gái của Chưởng môn phái Hành Dương đã quay về 500 năm trước để ngăn chặn chàng hoá ma.',
    actor: 'La Vân Hi, Bạch Lộc, Trần Đô Linh, Đặng Vi, Tôn Trân Ni',
    director: 'Cúc Giác Lượng',
    episodes: Array.from({ length: 40 }, (_, i) => ({
      id: `tntm-ep-${i + 1}`,
      movie_id: 'truong-nguyet-tan-minh',
      server: 'Server VIP (K-Vietsub)',
      name: `Tập ${String(i + 1).padStart(2, '0')}`,
      slug: `tap-${i + 1}`,
      type: 'm3u8',
      link: 'https://v7.kkphimplayer7.com/20260831/ljjy0751/index.m3u8'
    }))
  },
  {
    name: 'Vụng Trộm Không Thể Giấu',
    origin_name: 'Hidden Love',
    slug: 'vung-trom-khong-the-giau',
    thumb_url: 'https://image.tmdb.org/t/p/w500/4y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/5y7T2K9o2V4aT1v7w5Vb0Onv4bK.jpg',
    type: 'series',
    status: 'completed',
    episode_time: '45 phút/tập',
    episode_current: 'Hoàn Tất (25/25)',
    episode_total: '25',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2023,
    is_shown_in_theater: false,
    is_recommended: true,
    is_hot: true,
    view_total: 5800000,
    view_day: 55000,
    view_week: 410000,
    view_month: 1300000,
    rating_count: 14200,
    rating_star: '9.4',
    categories: [{ id: '2', name: 'Tình Cảm', slug: 'tinh-cam' }, { id: '80', name: 'Học Đường', slug: 'hoc-duong' }, { id: '3', name: 'Hài Hước', slug: 'hai-huoc' }],
    regions: [{ id: '1', name: 'Trung Quốc', slug: 'trung-quoc' }],
    description: 'Tang Trĩ từ thời cấp 2 đã thầm thương trộm nhớ Đoàn Gia Hứa – bạn thân của anh trai. Sau nhiều năm xa cách, khi gặp lại ở giảng đường đại học, tình cảm năm xưa lại bùng cháy.',
    actor: 'Triệu Lộ Tư, Trần Triết Viễn, Mã Bá Khiên, Tăng Lê, Khâu Tâm Chí',
    director: 'Lý Thanh Dung',
    episodes: Array.from({ length: 25 }, (_, i) => ({
      id: `vtktg-ep-${i + 1}`,
      movie_id: 'hidden-love',
      server: 'Server VIP (K-Vietsub)',
      name: `Tập ${String(i + 1).padStart(2, '0')}`,
      slug: `tap-${i + 1}`,
      type: 'm3u8',
      link: 'https://v7.kkphimplayer7.com/20260826/3hQ5mFzr/index.m3u8'
    }))
  },
  {
    name: 'Dune: Hành Tinh Cát (Phần 2)',
    origin_name: 'Dune: Part Two',
    slug: 'dune-hanh-tinh-cat-phan-2',
    thumb_url: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520bne.jpg',
    type: 'single',
    status: 'completed',
    episode_time: '166 phút',
    episode_current: 'Full HD',
    episode_total: '1',
    quality: 'FHD',
    language: 'Vietsub + Thuyết Minh',
    publish_year: 2024,
    is_shown_in_theater: true,
    is_recommended: true,
    is_hot: true,
    view_total: 4200000,
    view_day: 62000,
    view_week: 490000,
    view_month: 1400000,
    rating_count: 11200,
    rating_star: '9.5',
    categories: [{ id: '10', name: 'Viễn Tưởng', slug: 'vien-tuong' }, { id: '11', name: 'Phiêu Lưu', slug: 'phieu-luu' }, { id: '1', name: 'Hành Động', slug: 'hanh-dong' }],
    regions: [{ id: '46', name: 'Mỹ', slug: 'my' }, { id: '5', name: 'Âu Mỹ', slug: 'au-my' }],
    description: 'Paul Atreides hợp nhất với Chani và người Fremen trong khi tìm kiếm sự trả thù chống lại những kẻ âm mưu đã hủy diệt gia đình anh.',
    actor: 'Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem, Austin Butler',
    director: 'Denis Villeneuve',
    episodes: [
      { id: 'ep-dune2-1', movie_id: 'dune-2', server: 'Server VIP (K-Vietsub)', name: 'Full', slug: 'full-vip', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260820/Bg8E38Qv/index.m3u8' },
      { id: 'ep-dune2-2', movie_id: 'dune-2', server: 'Server Thuyết Minh', name: 'Full', slug: 'full-tm', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260826/57ip9H9r/index.m3u8' }
    ]
  },
  {
    name: 'Oppenheimer',
    origin_name: 'Oppenheimer',
    slug: 'oppenheimer-2023',
    thumb_url: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    poster_url: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    type: 'single',
    status: 'completed',
    episode_time: '180 phút',
    episode_current: 'Full HD',
    episode_total: '1',
    quality: 'FHD',
    language: 'Vietsub',
    publish_year: 2023,
    is_shown_in_theater: true,
    is_recommended: true,
    is_hot: true,
    view_total: 3900000,
    view_day: 42000,
    view_week: 360000,
    view_month: 1100000,
    rating_count: 10800,
    rating_star: '9.6',
    categories: [{ id: '16', name: 'Tài Liệu', slug: 'tai-lieu' }, { id: '18', name: 'Chính kịch', slug: 'chinh-kich' }, { id: '28', name: 'Chiến Tranh', slug: 'chien-tranh' }],
    regions: [{ id: '46', name: 'Mỹ', slug: 'my' }, { id: '5', name: 'Âu Mỹ', slug: 'au-my' }],
    description: 'Câu chuyện về nhà vật lý lý thuyết người Mỹ J. Robert Oppenheimer, người đóng vai trò then chốt trong Dự án Manhattan và sự phát triển của bom nguyên tử.',
    actor: 'Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr., Florence Pugh',
    director: 'Christopher Nolan',
    episodes: [
      { id: 'ep-opp-1', movie_id: 'oppenheimer', server: 'Server VIP (K-Vietsub)', name: 'Full', slug: 'full-vip', type: 'm3u8', link: 'https://v7.kkphimplayer7.com/20260826/3hQ5mFzr/index.m3u8' }
    ]
  }
];

let added = 0;
for (const m of extraMovies) {
  const existingIndex = db.movies.findIndex(x => x.slug === m.slug);
  const movieObj = {
    id: String(85000 + Math.floor(Math.random() * 10000)),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    deleted: false,
    hidden: false,
    ...m
  };
  if (existingIndex >= 0) {
    db.movies[existingIndex] = { ...db.movies[existingIndex], ...movieObj };
  } else {
    db.movies.unshift(movieObj);
    added++;
  }
}

fs.writeFileSync(dataFile, JSON.stringify(db, null, 2));
fs.writeFileSync(catalogFile, JSON.stringify(db.movies, null, 2));

console.log(`Successfully added/updated ${extraMovies.length} movies (${added} new). Total movies now: ${db.movies.length}`);
