import React, { useContext, useEffect, useState } from 'react';
import { Context } from './App';
import { api, normalize, number } from './api';

const f=(key,label,type='text',options)=>({key,label,type,options});
const publish=[f('status','Trạng thái','select',['draft','published','scheduled']),f('publish_at','Hẹn giờ xuất bản','datetime-local')];
const seo=[f('seo_title','SEO Title'),f('seo_description','SEO Description','textarea'),f('keywords','Keywords'),f('canonical','Canonical URL'),f('og_image','OG Image','image')];
const people=[f('name','Tên', 'required'),f('slug','Slug'),f('image','Ảnh','image'),f('biography','Tiểu sử','textarea'),f('country','Quốc gia'),f('movie_slugs','Phim tham gia','movies')];
export const contentModules={
  'video-servers':{title:'Server video',fields:[f('name','Tên server','required'),f('base_url','URL server'),f('enabled','Bật server','boolean'),f('is_default','Server mặc định','boolean')]},
  actors:{title:'Diễn viên',fields:people},directors:{title:'Đạo diễn',fields:people},
  trending:{title:'Phim HOT',fields:[f('title','Tên danh sách','required'),f('period','Bảng xếp hạng','select',['today','week','month','views','rating','featured']),f('movie_slugs','Chọn và sắp xếp phim','movies'),f('enabled','Hiển thị','boolean')]},
  homepage:{title:'Các khu vực trang chủ',fields:[f('title','Tên khu vực','required'),f('key','Mã khu vực'),f('movie_slugs','Chọn và sắp xếp phim','movies'),f('limit','Số phim hiển thị','number'),f('enabled','Hiển thị','boolean')]},
  banners:{title:'Banner',fields:[f('title','Tiêu đề','required'),f('description','Mô tả','textarea'),f('image','Ảnh','image'),f('slug','Phim liên kết','movie'),f('enabled','Hiển thị','boolean')]},
  schedule:{title:'Lịch phát hành',fields:[f('title','Tiêu đề','required'),f('movie_slug','Phim','movie'),f('episode','Tập'),f('publish_at','Thời điểm phát hành','datetime-local'),f('status','Trạng thái','select',['planned','released','cancelled'])]},
  notifications:{title:'Thông báo trong website',fields:[f('title','Tiêu đề','required'),f('body','Nội dung','textarea'),f('type','Loại','select',['movie','episode','maintenance','system','update']),f('movie_slug','Phim liên quan','movie'),f('publish_at','Thời điểm hiển thị','datetime-local'),f('enabled','Hiển thị','boolean')]},
  ads:{title:'Quảng cáo',fields:[f('title','Tên quảng cáo','required'),f('image','Ảnh','image'),f('link','URL đích'),f('position','Vị trí','select',['header','sidebar','player','footer']),f('starts_at','Bắt đầu','datetime-local'),f('ends_at','Kết thúc','datetime-local'),f('enabled','Hiển thị','boolean')]},
  posts:{title:'Bài viết',fields:[f('title','Tiêu đề','required'),f('slug','Slug'),f('excerpt','Tóm tắt','textarea'),f('body','Nội dung','textarea'),f('image','Ảnh','image'),...publish,...seo]},
  pages:{title:'Trang nội dung',fields:[f('title','Tiêu đề','required'),f('slug','Slug (about, contact, faq, terms, privacy...)'),f('body','Nội dung','textarea'),...publish,...seo]},
  languages:{title:'Ngôn ngữ',fields:[f('name','Tên ngôn ngữ','required'),f('code','Mã ngôn ngữ (vi, en, ko, zh)','required'),f('enabled','Bật','boolean'),f('is_default','Mặc định','boolean')]}
};
const translated={draft:'Bản nháp',published:'Đã xuất bản',scheduled:'Hẹn giờ',planned:'Theo lịch',released:'Đã phát hành',cancelled:'Đã hủy',today:'Hot hôm nay',week:'Hot tuần',month:'Hot tháng',views:'Top lượt xem',rating:'Top đánh giá',featured:'Nổi bật',movie:'Phim mới',episode:'Tập mới',maintenance:'Bảo trì',system:'Hệ thống',update:'Cập nhật',header:'Đầu trang',sidebar:'Thanh bên',player:'Trình phát',footer:'Cuối trang'};
const localDate=value=>{if(!value)return ''; const d=new Date(value);return Number.isNaN(d.getTime())?'':new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};

export function MovieSelection({value=[],onChange,movies}){
  const [query,setQuery]=useState('');
  function move(i,step){const list=[...value];if(i+step<0||i+step>=list.length)return;[list[i],list[i+step]]=[list[i+step],list[i]];onChange(list);}
  return <div className="movie-selection"><input aria-label="Lọc phim để chọn" placeholder="Tìm phim để thêm..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Thêm phim vào danh sách" value="" onChange={e=>{if(e.target.value)onChange([...value,e.target.value]);}}><option value="">＋ Chọn phim</option>{movies.filter(m=>!m.deleted&&!value.includes(m.slug)&&normalize(m.name).includes(normalize(query))).map(m=><option key={m.slug} value={m.slug}>{m.name}</option>)}</select>{value.map((slug,i)=><div className="admin-ranking" key={slug} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));if(!Number.isInteger(from)||from<0||from>=value.length)return;const list=[...value];list.splice(i,0,list.splice(from,1)[0]);onChange(list);}}><span>☰ {i+1}. {movies.find(m=>m.slug===slug)?.name||slug}</span><button type="button" onClick={()=>move(i,-1)} disabled={!i}>↑</button><button type="button" onClick={()=>move(i,1)} disabled={i===value.length-1}>↓</button><button type="button" aria-label={'Bỏ phim '+slug} onClick={()=>onChange(value.filter(x=>x!==slug))}>×</button></div>)}</div>;
}

export function ContentManager({kind,data}){
  const config=contentModules[kind];const {notify}=useContext(Context);
  const [items,setItems]=useState([]),[error,setError]=useState(''),[draft,setDraft]=useState(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[trash,setTrash]=useState(false),[calendar,setCalendar]=useState('all');
  const base='/admin/content/'+kind;
  async function load(){const result=await api(base);setItems(result.items);setError('');}
  useEffect(()=>{load().catch(e=>setError(e.message));},[kind]); // eslint-disable-line react-hooks/exhaustive-deps
  async function run(fn){setBusy(true);try{await fn();await load();notify('Đã cập nhật.');}catch(e){notify(e.message);}finally{setBusy(false);}}
  const fresh=()=>Object.fromEntries(config.fields.map(x=>[x.key,x.type==='boolean'?x.key==='enabled':x.type==='movies'?[]:x.type==='select'?x.options[0]:x.key==='limit'?10:'']));
  function upload(e,key){const file=e.target.files[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2000000)return notify('Chọn ảnh PNG/JPG/WebP dưới 2 MB.');const reader=new FileReader();reader.onload=()=>setDraft(v=>({...v,[key]:reader.result}));reader.readAsDataURL(file);}
  async function reorder(i,step){const ordered=items.filter(x=>!x.deleted);if(i+step<0||i+step>=ordered.length)return;[ordered[i],ordered[i+step]]=[ordered[i+step],ordered[i]];await run(()=>api(base+'/order','PUT',{ids:ordered.map(x=>x.id)}));}
  const visible=items.filter(x=>!!x.deleted===trash&&normalize([x.name,x.title,x.slug,x.code].join(' ')).includes(normalize(query))).filter(x=>kind!=='schedule'||calendar==='all'||(new Date(x.publish_at)>=new Date()&&new Date(x.publish_at)<=new Date(Date.now()+(calendar==='week'?7:31)*86400000)));
  return <section className="panel"><div className="section-heading"><h2>{config.title}</h2><button className="primary-button" onClick={()=>setDraft(fresh())}>＋ Thêm mới</button></div>{error&&<p role="alert">{error}</p>}
    {draft&&<form className="module-editor" onSubmit={async e=>{e.preventDefault();const body={...draft};config.fields.filter(x=>x.type==='datetime-local').forEach(x=>{if(body[x.key])body[x.key]=new Date(body[x.key]).toISOString();});await run(async()=>{await api(base+(draft.id?'/'+encodeURIComponent(draft.id):''),draft.id?'PUT':'POST',body);setDraft(null);});}}><h3>{draft.id?'Chỉnh sửa':'Thêm mới'}</h3><div className="form-grid">{config.fields.map(field=>{const {key,label,type,options}=field;const update=value=>setDraft(v=>({...v,[key]:value}));return <div key={key} className={['textarea','movies'].includes(type)?'field-wide':''}><label>{label}{type==='boolean'?<input type="checkbox" checked={!!draft[key]} onChange={e=>update(e.target.checked)}/>:type==='select'?<select value={draft[key]||options[0]} onChange={e=>update(e.target.value)}>{options.map(x=><option key={x} value={x}>{translated[x]||x}</option>)}</select>:type==='movie'?<select value={draft[key]||''} onChange={e=>update(e.target.value)}><option value="">Chọn phim</option>{data.movies.filter(m=>!m.deleted).map(m=><option key={m.slug} value={m.slug}>{m.name}</option>)}</select>:type==='movies'?null:type==='textarea'?<textarea rows={key==='body'?10:3} value={draft[key]||''} onChange={e=>update(e.target.value)}/>:<input required={type==='required'} type={type==='number'?'number':type==='datetime-local'?'datetime-local':'text'} value={type==='datetime-local'?localDate(draft[key]):draft[key]??''} onChange={e=>update(type==='number'?Number(e.target.value):e.target.value)}/>}</label>{type==='movies'&&<MovieSelection movies={data.movies} value={draft[key]} onChange={update}/ >}{type==='image'&&<><input aria-label={'Tải '+label} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e,key)}/>{draft[key]&&/^(https?:|\/storage\/|data:image\/)/.test(draft[key])&&<img className="admin-preview" src={draft[key]} alt={label}/>}</>}</div>;})}</div><button disabled={busy} className="primary-button">{busy?'Đang lưu...':'Lưu'}</button><button type="button" onClick={()=>setDraft(null)}>Hủy</button></form>}
    <div className="admin-filters"><input aria-label={'Tìm '+config.title} placeholder="Tìm kiếm..." value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Trạng thái danh sách" value={String(trash)} onChange={e=>setTrash(e.target.value==='true')}><option value="false">Đang quản lý</option><option value="true">Đã xóa</option></select>{kind==='schedule'&&<select aria-label="Khoảng lịch" value={calendar} onChange={e=>setCalendar(e.target.value)}><option value="all">Tất cả lịch</option><option value="week">7 ngày tới</option><option value="month">Tháng tới</option></select>}</div><div className="table-scroll"><table><thead><tr><th>Tên / Tiêu đề</th><th>Trạng thái / Chi tiết</th><th>Thao tác</th></tr></thead><tbody>{visible.map((x)=><tr key={x.id}><td>{x.title||x.name}<small className="admin-subtext">{x.slug||x.code||x.period||x.base_url}</small></td><td>{x.deleted?'Đã xóa':x.status?translated[x.status]||x.status:x.enabled===false?'Tắt':'Hiển thị'}{x.publish_at&&<small className="admin-subtext">{new Date(x.publish_at).toLocaleString('vi-VN')}</small>}{x.movie_slugs&&<small>{x.movie_slugs.length} phim</small>}{kind==='ads'&&<small className="admin-subtext">{number(x.impressions)} hiển thị · {number(x.clicks)} click</small>}{x.last_check&&<details><summary>Kiểm tra gần nhất</summary><pre>{JSON.stringify(x.last_check,null,2)}</pre></details>}</td><td><button disabled={busy} onClick={()=>setDraft({...fresh(),...x})}>Sửa</button>{!x.deleted&&<><button disabled={busy} onClick={()=>reorder(items.filter(v=>!v.deleted).findIndex(v=>v.id===x.id),-1)}>↑</button><button disabled={busy} onClick={()=>reorder(items.filter(v=>!v.deleted).findIndex(v=>v.id===x.id),1)}>↓</button></>}<button disabled={busy} onClick={()=>run(()=>api(base+'/'+encodeURIComponent(x.id)+(x.deleted?'/restore':''),x.deleted?'POST':'DELETE'))}>{x.deleted?'Khôi phục':'Xóa'}</button>{kind==='video-servers'&&<button disabled={busy} onClick={()=>run(async()=>{const result=await api(base+'/'+x.id+'/check','POST',{});notify(JSON.stringify(result));})}>Kiểm tra server</button>}</td></tr>)}</tbody></table></div>{!visible.length&&<p>Chưa có dữ liệu phù hợp.</p>}
  </section>;
}
